### ISSUE TITLE
'publicity emails' link is broke on campus.openhatch.org

### ISSUE THREAD

**Issue by possibly** [openhatch/open-source-comes-to-campus#111]
Just as the title says. You can find the broken link under 'Publicity Support' on this page: http://campus.openhatch.org/. When you click the link, it opens up Google Drive which promptly gives you the attached error message. Seems Shauna moved a folder to the trash.

This seems to be an up to date source: https://openhatch.org/wiki/Email_templates#Publicity_Emails

![screen shot 2015-03-25 at 8 38 54 pm](https://cloud.githubusercontent.com/assets/1417341/6840011/8dec159c-d32e-11e4-84d8-1430ea8320ec.png)
![screen shot 2015-03-25 at 8 39 01 pm](https://cloud.githubusercontent.com/assets/1417341/6840010/8deaf482-d32e-11e4-800c-76f7527794f1.png)

**Comment by shaunagm** [comment]
Good catch!  Fixed here:
https://github.com/openhatch/oh-campus-foss/commit/e360724db92c7e3175c49e50ccb73ac908b3bd06
