### ISSUE TITLE
Retire OSCTC-planning repo & google drive folder 

### ISSUE THREAD

**Issue by shaunagm** [openhatch/open-source-comes-to-campus#115]
Steps:
- [x] Go through repo and make sure info/functionality has been adequately captured by wiki, discourse, etc.
- [x] Prominently display at locations a statement saying we're no longer using them and redirecting them appropriately

**Comment by shaunagm** [comment]
Stuff in google doc:
- sign up forms & exit surveys: now on events.openhatch.org
- publicity spreadsheet: now just a suggestion in the publicity intro on Discourse
- templates: some are redundant due to events.openhatch.org, others are on discourse [here](http://discourse.openhatch.org/t/publicity-email-templates/141) and [here](http://discourse.openhatch.org/t/about-the-recruiting-organizing-volunteers-category/42)

Stuff in osctc-planning repo:
- introduction: now in this Discourse post: http://discourse.openhatch.org/t/getting-started/142
- trello board embed: also linked in that discourse thread
- timeline: now on wiki: https://openhatch.org/wiki/Open_Source_Comes_to_Campus/Logistics#How_much_time_do_we_need_to_plan.3F
- Quick links: pretty much redundant at this point.  There's nothing there that isn't linked elsewhere.

**Comment by paulproteus** [comment]
Whoa, amazing.​

**Comment by dcwalk** [comment]
Awesome!
