### ISSUE TITLE
Make sure Puppet Labs' Bronze sponsorship is sent to student attendees

### ISSUE THREAD

**Issue by paulproteus** [openhatch/open-source-comes-to-campus#57]
We promised that Bronze sponsors would get placement in "all email announcements" about the program. We probably don't mean every single email we send to students... but maybe we do mean every student is exposed to their name at least once by email.

If so, good places to include it are:

* The initial advertising emails that we ask local hosts to forward around

* For schools where we forgot to do it in the above, but haven't sent an exit survey, we could make sure to mention their names in the email that says, "Please take our exit survey"

* For schools where it's past exit survey time, since we've been adding students to the osctc-alumni announcement-oriented list, we could mention how great Puppet Labs has been, as part of the next email blast we send there

**Comment by dcwalk** [comment]
Closed as the issue no longer needs to be addressed (out of date).
