### ISSUE TITLE
 include GIMP and Inkscape logos on the OSCTC tools lecture logos slide

### ISSUE THREAD

**Issue by benmarwick** [openhatch/open-source-comes-to-campus#88]
Some of the apps currently on that slide might be a bit esoteric to
many undergrads. Probably you've put a lot of thought into the
sample represented there, but how about adding QGIS, GIMP, Inkscape,
Scribus, and LibreOffice? That would show that open source includes
'common or garden' software, and that there are viable OS
alternatives for products that students probably use often. I would
guess that Firefox might be the only logo that the average non-CS
student would recognise. 

I'd include GIMP and Inkscape since Photoshop 
and Illustrator are brands that have become generic and are probably 
household names for most students, regardless of their area of study.

**Comment by shaunagm** [comment]
See #93
