### ISSUE TITLE
Document mail merge form foibles

### ISSUE THREAD

**Issue by codersquid** [openhatch/open-source-comes-to-campus#89]
* When you copy the mail merge form it doesn't copy its mail merge status.
* It only allowed me to send 50 emails, so if you BCC yourself you reach your limit if you have 50 signups.
* The form requires a lot of permissions.
* The form allows html markup in the email, but it wasn't obvious to me. Include that as a tip in the docs.

I'd recommend picking a different way to send mails rather than using this form.

**Comment by shaunagm** [comment]
Bridgetroll (https://github.com/shaunagm/bridge_troll/) takes care of mass emails for us now, so I'm closing this.
